name: flopy
channels:
  - conda-forge
  - defaults
dependencies:
  - appdirs
  - requests
  - numpy
  - matplotlib
  - affine
  - scipy
  - pandas
  - netcdf4
  - pyshp
  - rasterio
  - fiona
  - descartes
  - pyproj
  - shapely
