name: flopy
channels:
  - conda-forge
  - defaults
dependencies:
  - pylint
  - flake8
  - black
  - nose
  - nose-timer
  - nose-cov
  - appdirs
  - requests
  - numpy
  - matplotlib
  - affine
  - scipy
  - pandas
  - netcdf4
  - pyshp
  - rasterio
  - fiona
  - descartes
  - pyproj
  - shapely
