[build-system]
# Minimum requirements for the build system to execute
requires = [
    "setuptools>45",
    "wheel",
]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 79
target_version = ["py37"]

[tool.isort]
profile = "black"
src_paths = ["flopy"]
line_length = 79
