"""
mfdrn module.  Contains the ModflowDrn class. Note that the user can access
the ModflowDrn class as `flopy.modflow.ModflowDrn`.

Additional information for this MODFLOW package can be found at the `Online
MODFLOW Guide
<http://water.usgs.gov/ogw/modflow/MODFLOW-2005-Guide/index.html?drn.htm>`_.

"""
import sys
import numpy as np
from flopy.mbase import Package
from flopy.utils.util_list import mflist


class ModflowDrn(Package):
    """
    MODFLOW Drain Package Class.

    Parameters
    ----------
    model : model object
        The model object (of type :class:`flopy.modflow.mf.Modflow`) to which
        this package will be added.
    idrncb : int
        is a flag and a unit number. (the default is 0).
    layer_row_column_data : list of records
        In its most general form, this is a triple list of drain records  The
        innermost list is the layer, row, column, elevation and conductance for
        a single drain.  Then for a stress period, there can be a list of
        drains.  Then for a simulation, there can be a separate list for each
        stress period. This gives the form of
            lrcd = [
                     [  #stress period 1
                       [l1, r1, c1, elev1, cond1],
                       [l2, r2, c2, elev2, cond2],
                       [l3, r3, c3, elev3, cond3],
                       ],
                     [  #stress period 2
                       [l1, r1, c1, elev1, cond1],
                       [l2, r2, c2, elev2, cond2],
                       [l3, r3, c3, elev3, cond3],
                       ], ...
                     [  #stress period kper
                       [l1, r1, c1, elev1, cond1],
                       [l2, r2, c2, elev2, cond2],
                       [l3, r3, c3, elev3, cond3],
                       ],
                    ]
        Note that if there are not records in layer_row_column_data, then the
        last group of drains will apply until the end of the simulation.
    layer_row_column_elevation_cond : list of records
        Deprecated - use layer_row_column_data instead.
    options : list of strings
        Package options. (default is None).
    naux : int
        number of auxiliary variables
    extension : string
        Filename extension (default is 'drn')
    unitnumber : int
        File unit number (default is 21).

    Attributes
    ----------
    mxactd : int
        Maximum number of drains for a stress period.  This is calculated
        automatically by FloPy based on the information in
        layer_row_column_data.

    Methods
    -------

    See Also
    --------

    Notes
    -----
    Parameters are not supported in FloPy.

    Examples
    --------

    >>> import flopy
    >>> m = flopy.modflow.Modflow()
    >>> lrcd = {0:[[2, 3, 4, 10., 100.]]}  #this drain will be applied to all
    >>>                                  #stress periods
    >>> drn = flopy.modflow.ModflowDrn(m, stress_period_data=lrcd)
    """
    def __init__(self, model, ipakcb=0, stress_period_data=None, dtype=None,
                 extension ='drn', unitnumber=21, options=None, **kwargs):
        """
        Package constructor
        """
        Package.__init__(self, model, extension, 'DRN', unitnumber) # Call ancestor's init to set self.parent, extension, name and unit number
        self.heading = '# DRN for MODFLOW, generated by Flopy.'
        self.url = 'drn.htm'
        self.ipakcb = ipakcb  # 0: no cell by cell terms are written

        self.np = 0
        if options is None:
            options = []
        self.options = options
        if dtype is not None:
            self.dtype = dtype
        else:
            self.dtype = self.get_default_dtype()
        self.stress_period_data = mflist(model, self.dtype, stress_period_data)
        self.parent.add_package(self)

    def __repr__( self ):
        return 'Drain class'

    @staticmethod
    def get_default_dtype():
        dtype = np.dtype([("k",np.int),("i",np.int),\
                         ("j",np.int),("elev",np.float32),\
                        ("cond",np.float32)])
        return dtype

    def ncells( self):
        # Returns the  maximum number of cells that have drains (developped for MT3DMS SSM package)
        #print 'Function must be implemented properly for drn package'
        return self.stress_period_data.mxact

    def write_file(self):
        """
        Write the file.

        """
        f_drn = open(self.fn_path, 'w')
        f_drn.write('{0}\n'.format(self.heading))
        #f_drn.write('%10i%10i\n' % (self.mxactd, self.idrncb))
        line = '{0:10d}{1:10d}'.format(self.stress_period_data.mxact, self.ipakcb)
        for opt in self.options:
            line += ' ' + str(opt)
        line += '\n'
        f_drn.write(line)
        self.stress_period_data.write_transient(f_drn)
        f_drn.close()

    def add_record(self,kper,index,values):
        try:
            self.stress_period_data.add_record(kper, index, values)
        except Exception as e:
            raise Exception("mfdrn error adding record to list: "+str(e))


    @staticmethod
    def get_empty(ncells=0,aux_names=None):
        #get an empty recaray that correponds to dtype
        dtype = ModflowDrn.get_default_dtype()
        if aux_names is not None:
            dtype = Package.add_to_dtype(dtype,aux_names,np.float32)
        d = np.zeros((ncells,len(dtype)),dtype=dtype)
        d[:,:] = -1.0E+10
        return np.core.records.fromarrays(d.transpose(),dtype=dtype)

    @staticmethod
    def load(f, model, nper=None, ext_unit_dict=None):

        if model.verbose:
            sys.stdout.write('loading drn package file...\n')

        return Package.load(model,ModflowDrn,f,nper)
