# ETS input file for ets1 and etsdrt test cases
#
  1  0  1  2           Item 1: NETSOP IETSCB NPETS NETSEG
ETS-Max  ETS  0.01  1  Item 2: PARNAM PARTYP PARVAL NCLU 
none       all         Item 3: Mltarr Zonarr
  1  1  1  0  1        Item 4: INETSS INETSR INETSX INIETS INSGDF, period 1
CONSTANT  100.0        Item 5: ETSS
ETS-Max                Item 7: Pname
constant  36.0         Item 8: ETSX
constant   0.5         Item 10: PXDP
constant   0.1         Item 11: PETM
