name: pyclass
channels:
  - conda-forge
dependencies:
  - numpy
  - matplotlib
  - xarray
  - requests
  - pandas
  - python-dateutil
  - xlrd
  - gdal
  - geopandas
  - rtree
  - descartes
  - shapely
  - scipy
  - netcdf4
  - pyproj>=2.0
  - rasterio>=1.0
  - rasterstats
  - pyshp
  - pip
