name: flopy
channels:
  - conda-forge
dependencies:
  # required
  - python>=3.8
  - numpy>=1.15.0
  - matplotlib>=1.4.0

  # optional
  - python-dateutil>=2.4.0
  - affine
  - scipy
  - pandas
  - netcdf4
  - pyshp
  - rasterio
  - fiona
  - descartes
  - pyproj
  - shapely>=1.8
  - geos
  - geojson
  - vtk
  - rasterstats
  - pyvista
  - imageio

  # MODFLOW API dependencies
  - bmipy
