name: flopy
channels:
  - conda-forge
dependencies:
  - conda-forge::python
  - conda-forge::numpy
  - conda-forge::matplotlib
  - conda-forge::affine
  - conda-forge::scipy
  - conda-forge::pandas
  - conda-forge::netcdf4
  - conda-forge::pyshp
  - conda-forge::rasterio
  - conda-forge::fiona
  - conda-forge::descartes
  - conda-forge::pyproj
  - conda-forge::shapely
  - conda-forge::geos=3.8.1  # required until 3.9.2 is available
  - conda-forge::geojson
  - conda-forge::pip
