# ---
# jupyter:
#   jupytext:
#     cell_metadata_filter: -all
#     formats: ipynb,py:light
#     text_representation:
#       extension: .py
#       format_name: light
#       format_version: '1.5'
#       jupytext_version: 1.17.2
#   kernelspec:
#     display_name: Python 3 (ipykernel)
#     language: python
#     name: python3
# ---

# # MODFLOW 6: MODFLOW 6 NetCDF inputs from FloPy simulation
#
# ## Write MODFLOW 6 NetCDF simulation
#
# This tutorial demonstrates how to generate a MODFLOW 6 NetCDF file
# from an existing FloPy simulation. Two variations will be shown.
# In the first, FloPy will generate the file with a modified
# `write_simulation()` call.  The second method is more interactive,
# providing an opputinity to modify the dataset before it is written
# to NetCDF.
#
# Support for generating a MODFLOW 6 NetCDF input without a defined
# FloPy mf6 model or package instances is briefly discussed at the
# end of the tutorial.
#
# For more information on supported MODFLOW 6 NetCDF formats see:
# [MODFLOW NetCDF Format](https://github.com/MODFLOW-ORG/modflow6/wiki/MODFLOW-NetCDF-Format).
#
# Note that NetCDF is only supported by the Extended version of MODFLOW 6.
# A nightly windows build of Extended MODFLOW 6 is available from
# [nightly build](https://github.com/MODFLOW-ORG/modflow6-nightly-build).

# package import
import sys
from pathlib import Path
from pprint import pformat, pprint
from tempfile import TemporaryDirectory

import git
import numpy as np
import pooch
import xarray as xr

import flopy

print(sys.version)
print(f"flopy version: {flopy.__version__}")

sim_name = "uzf01"

# Check if we are in the repository and define the data path.

try:
    root = Path(git.Repo(".", search_parent_directories=True).working_dir)
except:
    root = None

data_path = root / "examples" / "data" / "mf6" / "netcdf" if root else Path.cwd()

file_names = {
    "mfsim.nam": None,
    "uzf01.dis": None,
    "uzf01.ghb.obs": None,
    "uzf01.ghbg": None,
    "uzf01.ic": None,
    "uzf01.ims": None,
    "uzf01.nam": None,
    "uzf01.npf": None,
    "uzf01.obs": None,
    "uzf01.oc": None,
    "uzf01.sto": None,
    "uzf01.tdis": None,
    "uzf01.uzf": None,
    "uzf01.uzf.obs": None,
}

for fname, fhash in file_names.items():
    pooch.retrieve(
        url=f"https://github.com/modflowpy/flopy/raw/develop/examples/data/{sim_name}/{fname}",
        fname=fname,
        path=data_path / sim_name,
        known_hash=fhash,
    )

# ## Create simulation workspace

# create temporary directories
temp_dir = TemporaryDirectory()
workspace = Path(temp_dir.name)

# ## Load and run baseline simulation
#
# For the purposes of this tutorial, the specifics of the simulation
# other than it is a candidate for NetCDF input are not a focus. It
# is a NetCDF input candidate because it defines a supported model type
# (`GWF6`) with a structured discretization and packages that support
# NetCDF input parameters.
#
# More information about package NetCDF support in MODFLOW 6 can be
# found in the `MODFLOW 6 - Description of Input and Output` (`mf6io.pdf`),
# also available at the nightly build repository linked above.

# load and run the non-netcdf simulation
sim = flopy.mf6.MFSimulation.load(sim_ws=data_path / sim_name)
sim.set_sim_path(workspace)
sim.write_simulation()
success, buff = sim.run_simulation(silent=True, report=True)
assert success, pformat(buff)

# ## Create NetCDF based simulation method 1
#
# The most straightforward way to create a NetCDF simulation
# from the loaded simulation is to provide a `netcdf` argument
# to `write_simulation()` and define it to be either `structured`
# or `layered`, depending on the desired format of the generated
# NetCDF file.
#
# The name of the created file can be specified by first setting the
# model `name_file.nc_filerecord` attribute to the desired name. If
# this step is not taken, the default name of `{model_name}.input.nc`
# is used.

# create directory for netcdf sim
sim.set_sim_path(workspace / "netcdf1")
# set model name file nc_filerecord attribute to export name
gwf = sim.get_model("uzf01")
gwf.name_file.nc_filerecord = "uzf01.structured.nc"
# write simulation with structured NetCDF file
sim.write_simulation(netcdf="structured")

# ## Run MODFLOW 6 simulation with NetCDF input
#
# The simulation generated by this tutorial should run with the
# Extended MODFLOW 6 executable, available from the nightly-build
# repository (linked above).

# success, buff = sim.run_simulation(silent=True, report=True)
# assert success, pformat(buff)

# ## Repeat method 1 with layered mesh NetCDF format

# create directory for netcdf sim
sim.set_sim_path(workspace / "netcdf2")
# set model name file nc_filerecord attribute to export name
gwf = sim.get_model("uzf01")
gwf.name_file.nc_filerecord = "uzf01.layered.nc"
# write simulation with with layered mesh NetCDF file
sim.write_simulation(netcdf="layered")

# ## Run MODFLOW 6 simulation with NetCDF input
#
# The simulation generated by this tutorial should run with the
# Extended MODFLOW 6 executable, available from the nightly-build
# repository (linked above).

# success, buff = sim.run_simulation(silent=True, report=True)
# assert success, pformat(buff)

# ## Create NetCDF based simulation method 2
#
# In this method we will set the FloPy `netcdf` argument to `nofile`
# when `write_simulation()` is called. As such, FloPy will not generate
# the NetCDF file automatically. We will manage the NetCDF file
# generation ourselves in method 2.
#
# Reset the simulation path and set the `GWF` name file `nc_filerecord`
# attribute to the name of the intended input NetCDF file. Display
# the resultant name file changes.
#
# When we write the updated simulation, all packages that support NetCDF
# input parameters will be written such that NetCDF parameters expect the
# data source to be a NetCDF file. We will therefore need to create a
# NetCDF input file containing arrays for the `DIS`, `NPF`, `IC`, `STO`,
# and `GHBG` packages. We will still use FloPy package objects to set the
# parameter data in the dataset; however an `update_data=False` argument
# could be passed to the `update_dataset()` call if this was not desired.

# create directory for netcdf sim
sim.set_sim_path(workspace / "netcdf3")
# set model name file nc_filerecord attribute to export name
gwf = sim.get_model("uzf01")
gwf.name_file.nc_filerecord = "uzf01.structured.nc"
# write simulation with ASCII inputs tagged for NetCDF
# but do not create NetCDF file
sim.write_simulation(netcdf="nofile")

# ## Show name file with NetCDF input configured

# show name file with NetCDF input configured
with open(workspace / "netcdf3" / "uzf01.nam", "r") as fh:
    print(fh.read())

# ## Show example package file with NetCDF keywords

# show example package file with NetCDF input configured
with open(workspace / "netcdf3" / "uzf01.ic", "r") as fh:
    print(fh.read())

# ## Create dataset
#
# Create the base xarray dataset from the modelgrid object. This
# will add required dimensions and coordinate variables to the
# dataset according to the grid specification. Modeltime is needed
# for timeseries support.

# create the dataset
ds = gwf.modelgrid.dataset(modeltime=gwf.modeltime)

# ## Access model NetCDF attributes
#
# Internally, FloPy generates and uses NetCDF metadata dictionaries
# to update datasets. Both model and package objects can generate
# the dictionaries and they contain related but distinct NetCDF
# details. Model object dictionaries contain file scoped attribute
# information while package dictionaries are organized by NetCDF
# variable and contain variable scoped attribute information and
# details related to creating the variable, including dimensions,
# shape and data type.
#
# The dictionaries are available via the `netcdf_info()` call. Their
# content also varies depending on the desired type of dataset (i.e.
# `structured` or `layered`). In this step we will access the model
# NetCDF metadata and use it to update dataset scoped attributes.
#
# First, retrieve and store the netcdf metadata dictionary and display
# its contents. Then, in the following step, update the dataset with
# the model scoped attributes defined in the dictionary.
#
# These operations can also both be accomplished by calling
# `update_dataset()` on the model object, albeit without the
# opportunity to modify the intermediate metadata dictionary.
# Examples of this approach (with package objects) are shown below.

# get model netcdf info
nc_info = gwf.netcdf_info()
pprint(nc_info)

# update dataset directly with required attributes
for a in nc_info["attrs"]:
    ds.attrs[a] = nc_info["attrs"][a]

# ## Update the dataset with supported `DIS` arrays
#
# First, we will show how package NetCDF parameters can be added to the
# dataset without using the NetCDF metadata dictionary. We will use the
# metadata dictionary when updating the dataset with NPF parameter data.
#
# Add NetCDF supported data arrays in package to dataset.

# update dataset with `DIS` arrays
dis = gwf.get_package("dis")
ds = dis.update_dataset(ds)

# ## Access `NPF` package NetCDF attributes
#
# Access package scoped NetCDF details by storing the dictionary returned
# from `netcdf_info()`.
#
# The contents of the info dictionary are shown and then, in the following
# step, the dictionary and the dataset are passed to a helper routine that
# create the intended array variables.

# get npf package netcdf info
npf = gwf.get_package("npf")
nc_info = npf.netcdf_info()
pprint(nc_info)

# ## Update package NetCDF metadata dictionary and dataset
#
# Here we update the metadata dictionary and then pass it directly to the
# `update_dataset()` function which uses it when adding variables to the
# dataset.
#
# We replace the default name for the `NPF K` input parameter and add
# the `standard_name` attribute to it's attribute dictionary. The
# dictionary is then passed to the `update_dataset()` function. Note the
# updated name is used in the subsequent block when updating the array
# values.

# update dataset with `NPF` arrays
nc_info["k"]["varname"] = "npf_k_updated"
nc_info["k"]["attrs"]["standard_name"] = "soil_hydraulic_conductivity_at_saturation"
ds = npf.update_dataset(ds, netcdf_info=nc_info)

# ## Show dataset `NPF K` parameter with updates

# print dataset npf k variable
print(ds["npf_k_updated"])

# ## Update the dataset with supported `IC` arrays

# ic
ic = gwf.get_package("ic")
ds = ic.update_dataset(ds)

# ## Update the dataset with supported `STO` arrays

# storage
sto = gwf.get_package("sto")
ds = sto.update_dataset(ds)

# ## Update the dataset with supported `GHBG` arrays

# update dataset with 'GHBG' arrays
ghbg = gwf.get_package("ghbg_0")
ds = ghbg.update_dataset(ds)

# ## Display generated dataset

# show the dataset
print(ds)

# ## Export generated dataset to NetCDF

# write dataset to netcdf
ds.to_netcdf(
    workspace / "netcdf3" / "uzf01.structured.nc", format="NETCDF4", engine="netcdf4"
)

# ## Run MODFLOW 6 simulation with NetCDF input
#
# The simulation generated by this tutorial should run with the
# Extended MODFLOW 6 executable, available from the nightly-build
# repository (linked above).

# success, buff = sim.run_simulation(silent=True, report=True)
# assert success, pformat(buff)

# ## Method 3: DIY with xarray
#
# The above method still uses FloPy objects to update the dataset arrays
# to values consistent with the state of the objects. The `netcdf_info`
# dictionary is intended to supported creation of the dataset without
# an existing simulation defined. The base dataset can be defined with
# `modelgrid` and `modeltime` objects, while the full package netcdf
# dictionary can retrieved with a static call to a model or package mf6
# type. The auxiliary input is optional but does show the variables that
# would be required if auxiliary variables were defined in the package.

# ## Demonstrate static call on MFPackage (structured dataset):

netcdf_info = flopy.mf6.mfpackage.MFPackage.netcdf_package(
    mtype="GWF",
    ptype="NPF",
    auxiliary=["CONCENTRATION"],
)
pprint(netcdf_info)

# ## Demonstrate static call on MFPackage (layered dataset):

netcdf_info = flopy.mf6.mfpackage.MFPackage.netcdf_package(
    mtype="GWF", ptype="NPF", mesh="LAYERED", auxiliary=["CONCENTRATION"], nlay=2
)
pprint(netcdf_info)
